### ISSUE TITLE
Odoo Server Error When installing the module

### ISSUE THREAD

**Issue by msujanshakya** [mybizna/mybizna_isp#11]
Issue when installing in odoo 15. Please help. Its installed in windows machine

![image](https://user-images.githubusercontent.com/98091598/150332735-4e1c2804-1dfc-4f66-8337-3ec2f65d822d.png)

**Comment by dedanirungu** [comment]
Test now

**Comment by kenedizo** [comment]
I am getting the same error, I dont know what the issue is, am using windows 10 odoo 15, kindly assist

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\http.py", line 910, in call
    return self.method(*args, **kw)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\addons\web\controllers\main.py", line 1330, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\addons\web\controllers\main.py", line 1318, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\addons\base\models\ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\addons\base\models\ir_module.py", line 486, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\addons\base\models\ir_module.py", line 603, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\modules\loading.py", line 476, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\modules\loading.py", line 365, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\modules\loading.py", line 179, in load_module_graph
    load_openerp_module(package.name)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\modules\module.py", line 396, in load_openerp_module
    import('odoo.addons.' + module_name)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\addons\mybizna_isp\__init__.py", line 4, in <module>
    from . import models
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\addons\mybizna_isp\models\__init__.py", line 6, in <module>
    from . import connections
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\addons\mybizna_isp\models\connections.py", line 3, in <module>
    import mysql.connector as mysql
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files\Odoo 15.0.20230410\server\odoo\http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ModuleNotFoundError: No module named 'mysql'
