### ISSUE TITLE
getting error when installing in odoo

### ISSUE THREAD

**Issue by dibrakwach** [mybizna/mybizna_isp#12]
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "C:\odoo\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\odoo\server\odoo\http.py", line 688, in dispatch
    result = self._call_function(**self.params)
  File "C:\odoo\server\odoo\http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\odoo\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\odoo\server\odoo\http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\odoo\server\odoo\http.py", line 917, in __call__
    return self.method(*args, **kw)
  File "C:\odoo\server\odoo\http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "C:\odoo\server\odoo\addons\web\controllers\main.py", line 1339, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\odoo\server\odoo\addons\web\controllers\main.py", line 1327, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\odoo\server\odoo\api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\odoo\server\odoo\api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "C:\odoo\server\odoo\addons\base\models\ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\odoo\server\odoo\addons\base\models\ir_module.py", line 483, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\odoo\server\odoo\addons\base\models\ir_module.py", line 600, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\odoo\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "C:\odoo\server\odoo\modules\loading.py", line 476, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\odoo\server\odoo\modules\loading.py", line 365, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\odoo\server\odoo\modules\loading.py", line 179, in load_module_graph
    load_openerp_module(package.name)
  File "C:\odoo\server\odoo\modules\module.py", line 396, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "c:\users\25472\appdata\local\openerp s.a\odoo\addons\15.0\mybizna_isp\__init__.py", line 4, in <module>
    from . import models
  File "c:\users\25472\appdata\local\openerp s.a\odoo\addons\15.0\mybizna_isp\models\__init__.py", line 6, in <module>
    from . import connections
  File "c:\users\25472\appdata\local\openerp s.a\odoo\addons\15.0\mybizna_isp\models\connections.py", line 3, in <module>
    import mysql.connector as mysql
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\odoo\server\odoo\http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\odoo\server\odoo\http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ModuleNotFoundError: No module named 'mysql'

**Comment by gomezgleonardob** [comment]
# 👇️ in a virtual environment or using Python 2
pip install mysql-connector-python

# 👇️ for python 3 (could also be pip3.10 depending on your version)
pip3 install mysql-connector-python

Install Python-Connector

**Comment by ItsOkinda** [comment]
bruhh fix mysql installation first
